version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: ileplaca_blockchain_platform_frontend_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
  smart_contract:
    build: ./smart_contract
    container_name: ileplaca_blockchain_platform_smart_contract
    ports:
      - "8455:8455"